# /setup/roles/deck/tasks/main.yml
#
# ansible playbook file
#
# configures hosts for Cabrillo ROV 2023
# sub-playbook for deck configuration
#
# Copyright (C) 2022-2023 Cabrillo Robotics Club
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Cabrillo Robotics Club
# 6500 Soquel Drive Aptos, CA 95003
# cabrillorobotics@gmail.com
#
---

# the deck starts with ubuntu server and then we install the ubuntu-desktop package
# this is because ssh-server is not installed by default on ubuntu desktop and we need it to use ansible
# the deck gets the desktop version of ros
# we use rviz for the robot controller interface
- name: deck apt parts
  become: True
  become_user: root
  ansible.builtin.apt:
    name:
      - ubuntu-desktop
      - ros-humble-desktop
      - rviz
    state: present
    cache_valid_time: 86400
